# Generated by Django 3.1.7 on 2021-02-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltasks',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tareas'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'tareas', 'verbose_name_plural': 'Tareas'},
        ),
    ]
