# Generated by Django 3.1.7 on 2021-02-23 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20210223_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltasks',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuarios'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltasks',
            name='category_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.categorytask', verbose_name='Categoria de la tarea'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.categorytask', verbose_name='Categoria de la tarea'),
        ),
    ]
