# Generated by Django 3.1.7 on 2021-02-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210222_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
